##This script will contines libraries
#install.packages("dplyr")
#install.packages('taRifx')
#install.packages('rlist')
require('dplyr')
require('taRifx')
require('rlist')
require('purrr')
require('timeSeries')
require('fPortfolio')
require('microbenchmark')
require("comprehenr")
require('ggplot2')
require('tidyr')
require('reshape2')